### ISSUE TITLE
hardcoded parameters in proxysql_node_monitor script

### ISSUE THREAD

**Issue by fabtesta** [percona/proxysql-admin-tool#1]
In a multi hostgroup scenario, the script could lead to some problems.
Variable HOSTGROUP_ID (arg1 of scheduler config) is not used in statement at line 51.
`INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight) VALUES ('$ws_ip',10,$ws_port,1000);`
should be
`INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight) VALUES ('$ws_ip',$HOSTGROUP_ID,$ws_port,1000);`

Moreover the hostgroup id parameter is not included as a condition in statement at line 65.
`DELETE FROM mysql_servers WHERE hostname='$ws_ip' and port=$ws_port;`
should be
`DELETE FROM mysql_servers WHERE hostgroup_id=  $HOSTGROUP_ID and hostname='$ws_ip' and port=$ws_port;`

Again an hardcoded param ad line 73.
`UPDATE SCHEDULER SET arg3=${#wsrep_address[@]} WHERE id=10;LOAD SCHEDULER TO RUNTIME;SAVE SCHEDULER TO DISK;`
should be
`UPDATE SCHEDULER SET arg3=${#wsrep_address[@]} WHERE id=$HOSTGROUP_ID;LOAD SCHEDULER TO RUNTIME;SAVE SCHEDULER TO DISK;`

**Comment by rameshvs02** [comment]
Hi Fabtesta, 

Thank you for the bug report. Currently this tool does not support multi hostgroup scenario. Will be adding multi hostgroup support in future release.

Will fix hard coded hostgroup id issues.

Thanks,
Ramesh

**Comment by rameshvs02** [comment]
Fixed https://github.com/percona/proxysql-admin-tool/commit/2470d133f61116e60d5fa12ef1f8b6e71b29e03c
