### ISSUE TITLE
Undefined variable in proxysql_node_monitor

### ISSUE THREAD

**Issue by ethaniel** [percona/proxysql-admin-tool#34]
I've noticed that $HOSTGROUP_ID is not defined anywhere else in the code (or config).
Mistake?

![image](https://cloud.githubusercontent.com/assets/941973/22943566/8ecd75fa-f320-11e6-8984-e7dc8b1ef8cd.png)

**Comment by rameshvs02** [comment]
This issues is already fixed in v1.3.2-dev. Changes will be available in next release.
